In [35]:
import torch 
from torch.autograd import Variable

# 旧版本的Pytorch中，Variable是对Tensor的一个封装；在Pytorch大于v0.4的版本后，Varible和Tensor合并了，意味着Tensor可以像旧版本的Variable那样运行，当然新版本中Variable封装仍旧可以用，但是对Varieble操作返回的将是一个Tensor。

In [38]:
# tensor ->variable
x = Variable(t.ones(4,5))
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [39]:
# variable->tensor
y = x.data
y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

# 对于那些不是任何函数(Function)的输出，由用户创建的节点称为叶子节点，叶子节点的grad_fn为None。

In [26]:
a = torch.ones(3,requires_grad=True)
b = torch.rand(3,requires_grad=True)

print(a)
print(b)
print(a.grad)  #为None
a.is_leaf

tensor([1., 1., 1.], requires_grad=True)
tensor([0.3741, 0.2563, 0.1793], requires_grad=True)
None


True

In [27]:
c = a*b
c.is_leaf

False

In [28]:
a.grad_fn

In [29]:
c.grad_fn

In [30]:
d=c.sum()
print(d)
d.backward()


tensor(0.8097, grad_fn=<SumBackward0>)


# 只有requires_grad为True，且从其他节点调用函数backward()，则不为None。

In [31]:
print(a.grad)

tensor([0.3741, 0.2563, 0.1793])


# 首先Tensor是默认不需要求导的，即requires_grad默认为False。

In [10]:
a = torch.ones(3)
a.requires_grad

False

# 如果某一个节点requires_grad被设置为True，那么所有依赖它的节点requires_grad都为True

In [11]:
import torch as t
 
a = t.ones(3)
b = t.ones(3,requires_grad=True)
b.requires_grad
#输出：True
c = a + b
c.requires_grad
#输出：True.虽然c没有指定需要求导，然是c依赖于b，而b需要求导，所以c.requires_grad=True


True